build:
    environment:
        php:
            version: 7.2.17
            ini:
                'date.timezone': 'Asia/Tokyo'

    tests:
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'clover'
