tools:
    external_code_coverage: true
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
